Cleanup scripts to store generated files under gen/ subdirectory.
Signed-off-by: Ramon Pantin <pantin@google.com>
Change-Id: I8d785a9b3b5f2cecc52666992861426aed26875b

diff --git a/liblwt/run b/liblwt/run
--- a/liblwt/run
+++ b/liblwt/run
@@ -21,20 +21,25 @@ if [ "$ARCH" != x64 -a "$ARCH" = arm64 ] ; then
 	usage
 fi
 
+if [ ! -f gen/binaries-$ARCH ] ; then
+	echo "$CMD: file produced by mk is missing: gen/binaries-$ARCH" 1>&2
+	exit 1
+fi
+
 STEP_COUNT=100
 
 TEST_LIST=''
 
-TEST_LIST="$TEST_LIST ./test_schedq-g-x64"
-TEST_LIST="$TEST_LIST ./test_schedq-O3-g-x64"
-TEST_LIST="$TEST_LIST ./test_schedq-O3-x64"
-TEST_LIST="$TEST_LIST ./test-pthread-O3-g-x64"
+TEST_LIST="$TEST_LIST ./gen/test_schedq-g-x64"
+TEST_LIST="$TEST_LIST ./gen/test_schedq-O3-g-x64"
+TEST_LIST="$TEST_LIST ./gen/test_schedq-O3-x64"
+TEST_LIST="$TEST_LIST ./gen/test-pthread-O3-g-x64"
 
-# TEST_LIST="$TEST_LIST ./test_schedq-clang-g-x64"
+# TEST_LIST="$TEST_LIST ./gen/test_schedq-clang-g-x64"
 
 go()
 {
-	for TEST in $(cat binaries-$ARCH) $TEST_LIST ; do
+	for TEST in $(cat gen/binaries-$ARCH) $TEST_LIST ; do
 		echo -n "$TEST: "
 		$TEST
 		STATUS="$?"
