Fix a small bug and add benchmarks to explore sched_attempts values.
Signed-off-by: Ramon Pantin <pantin@google.com>
Change-Id: Ia50f1619588dbd72d9ed44298ab0d8b9a1499f69

diff --git a/liblwt/run b/liblwt/run
--- a/liblwt/run
+++ b/liblwt/run
@@ -1,17 +1,59 @@
-#!/usr/local/bin/bash
+#!/usr/bin/bash
 
-set -x
-set -e
+rm -f core
+ulimit -c unlimited
 
-./test-g-x64
-./test-O3-g-x64
-# ./test-O3-x64
+STEP_COUNT=100
 
-./test-mp-g-x64
-./test-mp-g-no-LWT_DEBUG-x64
-./test-mp-O3-g-x64
-./test-mp-O3-g-no-LWT_DEBUG-x64
-# ./test-mp-O3-x64
-# ./test-mp-O3-no-LWT_DEBUG-x64
+TEST_LIST=''
 
-./test-pthread-O3-g-x64
+TEST_LIST="$TEST_LIST ./test-g-x64"
+TEST_LIST="$TEST_LIST ./test-O3-g-x64"
+
+# TEST_LIST="$TEST_LIST ./test-O3-x64"
+
+TEST_LIST="$TEST_LIST ./test-mp-g-x64"
+TEST_LIST="$TEST_LIST ./test-mp-g-no-LWT_DEBUG-x64"
+TEST_LIST="$TEST_LIST ./test-mp-O3-g-x64"
+TEST_LIST="$TEST_LIST ./test-mp-O3-g-no-LWT_DEBUG-x64"
+
+# TEST_LIST="$TEST_LIST ./test-mp-O3-x64"
+# TEST_LIST="$TEST_LIST ./test-mp-O3-no-LWT_DEBUG-x64"
+
+TEST_LIST="$TEST_LIST ./test-pthread-O3-g-x64"
+
+go()
+{
+	for TEST in $TEST_LIST ; do
+		echo -n "$TEST: "
+		$TEST
+		STATUS="$?"
+
+		if [ "$STATUS" -eq 0 ] ; then
+			echo 'ok'
+			continue
+		fi
+
+		if [ -f core ] ; then
+			mv core "$TEST.core"
+			echo "FAILED: status = $STATUS: core dumped"
+			echo
+			echo "gdb $TEST $TEST.core"
+		else
+			echo "FAILED: status = $STATUS"
+		fi
+		return 1
+	done
+	return 0
+}
+
+STEP=0
+while [ $STEP -lt $STEP_COUNT ] ; do
+	if go ; then
+		:
+	else
+		exit 1
+	fi
+
+	STEP=$[ STEP + 1 ]
+done
